# Dependencies
markdown:         kramdown
highlighter:      pygments

# Permalinks
permalink:        pretty


# Setup
title:            Martini
tagline:          'A Jekyll theme'
description:      'Dream to develop my own game'
url:              http://hyde.getpoole.com
baseurl:          /

author:
  name:           'Martini'
  url:            /

paginate:         5

# Custom vars
version:          2.1.0

github:
  repo:           https://github.com/martinigv
